const state={data:{},filters:{segment:"all",perspective:"all",priority:"all",search:""}};
const files={meta:"data/meta.json",signals:"data/signals.json",competitors:"data/competitors.json",customers:"data/customers.json",technologies:"data/technologies.json",opportunities:"data/opportunities.json",risks:"data/risks.json",weekly:"data/weekly.json"};
async function loadData(){const entries=await Promise.all(Object.entries(files).map(async([key,path])=>{const res=await fetch(path);if(!res.ok)throw new Error(`Could not load ${path}`);return[key,await res.json()]}));state.data=Object.fromEntries(entries)}
const norm=v=>String(v||"").toLowerCase();
const badge=p=>`<span class="badge ${norm(p)}">${p}</span>`;
const segMatch=(value,seg)=>seg==="all"||norm(value).includes(norm(seg))||norm(value).includes("all offroad");
const searchMatch=obj=>!state.filters.search||norm(JSON.stringify(obj)).includes(norm(state.filters.search));
function filteredSignals(){return state.data.signals.filter(s=>segMatch(s.segment,state.filters.segment)&&(state.filters.perspective==="all"||s.perspective===state.filters.perspective)&&(state.filters.priority==="all"||s.priority===state.filters.priority)&&searchMatch(s))}
function setup(){document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.view).classList.add("active")}));const seg=document.getElementById("segmentFilter"),per=document.getElementById("perspectiveFilter");state.data.meta.segments.forEach(x=>seg.insertAdjacentHTML("beforeend",`<option value="${x}">${x}</option>`));state.data.meta.perspectives.forEach(x=>per.insertAdjacentHTML("beforeend",`<option value="${x}">${x}</option>`));seg.onchange=e=>{state.filters.segment=e.target.value;renderDashboardViews()};per.onchange=e=>{state.filters.perspective=e.target.value;renderDashboardViews()};document.getElementById("priorityFilter").onchange=e=>{state.filters.priority=e.target.value;renderDashboardViews()};document.getElementById("searchInput").oninput=e=>{state.filters.search=e.target.value;renderAll()};document.getElementById("resetFilters").onclick=()=>{state.filters={segment:"all",perspective:"all",priority:"all",search:""};seg.value="all";per.value="all";document.getElementById("priorityFilter").value="all";document.getElementById("searchInput").value="";renderAll()}}
function renderKpis(signals){const high=signals.filter(s=>s.priority==="High").length;const kpis=[["Signals",signals.length],["High priority",high],["Offroad segments",state.data.meta.segments.length],["Competitors",state.data.competitors.length],["Customers mapped",state.data.customers.length],["Tech themes",state.data.technologies.length]];document.getElementById("kpis").innerHTML=kpis.map(([l,v])=>`<article class="kpi"><span>${l}</span><strong>${v}</strong></article>`).join("")}
function renderPriority(signals){const sorted=[...signals].sort((a,b)=>(a.priority==="High"?-1:1)-(b.priority==="High"?-1:1)).slice(0,3);document.getElementById("priorityGrid").innerHTML=sorted.map((s,i)=>`<article class="signal-card"><div class="card-top">${badge(s.priority)}<span class="meta">${String(i+1).padStart(2,"0")}</span></div><div class="meta">${s.entity} · ${s.perspective}</div><h3>${s.signal}</h3><div><div class="label">Why it matters</div><p>${s.why}</p></div><div><div class="label">Recommended action</div><p>${s.action}</p></div></article>`).join("")}
function renderLatest(signals){document.getElementById("feedCount").textContent=`${signals.length} items`;document.getElementById("latestList").innerHTML=signals.map(s=>`<div class="compact-row"><div>${badge(s.priority)}<p class="meta">${s.perspective}</p></div><div><h4>${s.signal}</h4><p>${s.why}</p></div><div class="meta">${s.time}<br>${s.segment}</div></div>`).join("")}
function renderBars(signals){const counts=signals.reduce((a,s)=>(a[s.category]=(a[s.category]||0)+1,a),{});const max=Math.max(1,...Object.values(counts));document.getElementById("bars").innerHTML=Object.entries(counts).map(([n,c])=>`<div><div class="bar-label"><strong>${n}</strong><em>${c}</em></div><div class="track"><div class="fill" style="width:${c/max*100}%"></div></div></div>`).join("")}
function renderSignalsTable(){const signals=filteredSignals();document.getElementById("signalsTable").innerHTML=`<table><thead><tr><th>ID</th><th>Priority</th><th>Perspective</th><th>Segment</th><th>Signal</th><th>Why it matters</th><th>Recommended action</th><th>Owner</th></tr></thead><tbody>${signals.map(s=>`<tr><td>${s.id}</td><td>${badge(s.priority)}</td><td>${s.perspective}</td><td>${s.segment}</td><td><strong>${s.signal}</strong></td><td>${s.why}</td><td>${s.action}</td><td>${s.owner}</td></tr>`).join("")}</tbody></table>`}
function renderCompetitors(){const competitors=state.data.competitors.filter(searchMatch);const cards=competitors.map(c=>`<article class="profile-card"><div class="profile-cover"><div><div class="meta">${c.id} · ${c.positioning}</div><h3>${c.name}</h3></div>${badge(c.relevance)}</div><div class="profile-body"><p><strong>Segments:</strong> ${c.segments}</p><p><strong>Customer overlaps:</strong> ${c.customerOverlaps}</p><div class="profile-columns"><div class="info-box"><strong>Why GRAMMER wins</strong><ul>${c.whyWeWin.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="info-box"><strong>Why GRAMMER loses</strong><ul>${c.whyWeLose.map(x=>`<li>${x}</li>`).join("")}</ul></div></div><button class="detail-link" data-competitor="${c.id}">Open full profile</button></div></article>`).join("");document.getElementById("competitorGrid").innerHTML=cards+`<section id="competitorDetail" class="detail-panel"></section>`;document.querySelectorAll("[data-competitor]").forEach(b=>b.onclick=()=>showCompetitorDetail(b.dataset.competitor))}
function showCompetitorDetail(id){const c=state.data.competitors.find(x=>x.id===id);const relatedSignals=state.data.signals.filter(s=>norm(s.entity).includes(norm(c.name))||norm(c.segments).split(";").some(seg=>norm(s.segment).includes(norm(seg.trim()))));const relatedCustomers=state.data.customers.filter(customer=>customer.competitors.includes(c.name));const el=document.getElementById("competitorDetail");el.classList.add("active");el.innerHTML=`<div class="detail-header"><div><div class="meta">${c.id} · ${c.positioning}</div><h3>${c.name}</h3><p><strong>Segments:</strong> ${c.segments}</p></div><button class="close-detail" id="closeCompetitorDetail">Close</button></div><div class="detail-grid"><div class="detail-box"><strong>Strengths</strong><ul>${c.strengths.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-box"><strong>Weaknesses</strong><ul>${c.weaknesses.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-box"><strong>Questions to ask</strong><ul>${c.questions.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-box"><strong>Opportunities</strong><ul>${c.opportunities.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-box"><strong>Threats</strong><ul>${c.threats.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="detail-box"><strong>Counter-message</strong><p>${c.counterMessage}</p></div><div class="detail-box"><strong>Related customers</strong><ul>${relatedCustomers.map(x=>`<li>${x.customer}</li>`).join("")||"<li>No direct mapping yet</li>"}</ul></div><div class="detail-box"><strong>Related signals</strong><ul>${relatedSignals.slice(0,4).map(x=>`<li>${x.id}: ${x.signal}</li>`).join("")||"<li>No related signal yet</li>"}</ul></div><div class="detail-box"><strong>Update logic</strong><p>Update when a major signal appears or during monthly competitor review.</p></div></div>`;document.getElementById("closeCompetitorDetail").onclick=()=>el.classList.remove("active");el.scrollIntoView({behavior:"smooth",block:"start"})}
function renderCustomerMap(){document.getElementById("customerTable").innerHTML=`<table><thead><tr><th>Customer / OEM</th><th>Segment</th><th>Competitors</th><th>GRAMMER position</th><th>Risk</th><th>Opportunity</th><th>Next action</th></tr></thead><tbody>${state.data.customers.filter(searchMatch).map(c=>`<tr><td><strong>${c.customer}</strong></td><td>${c.segment}</td><td>${c.competitors.join("; ")}</td><td>${c.grammerPosition}</td><td>${badge(c.riskLevel)}</td><td>${badge(c.opportunityLevel)}</td><td>${c.nextAction}</td></tr>`).join("")}</tbody></table>`}
function renderTechnology(){document.getElementById("technologyGrid").innerHTML=state.data.technologies.filter(searchMatch).map(t=>`<article class="card"><div class="card-top"><h3>${t.theme}</h3>${badge(t.relevance)}</div><p><strong>Maturity:</strong> ${t.maturity}</p><p><strong>Affected segments:</strong> ${t.segments}</p><p><strong>Watch signals:</strong> ${t.watchSignals}</p><p><strong>Owner:</strong> ${t.owner}</p></article>`).join("")}
function renderRegisters(){document.getElementById("opportunityGrid").innerHTML=state.data.opportunities.filter(searchMatch).map(o=>`<article class="card"><div class="card-top"><span class="meta">${o.id}</span>${badge(o.priority)}</div><h3>${o.opportunity}</h3><p><strong>Segment:</strong> ${o.segment}</p><p><strong>Why attractive:</strong> ${o.why}</p><p><strong>Next action:</strong> ${o.nextAction}</p></article>`).join("");document.getElementById("riskGrid").innerHTML=state.data.risks.filter(searchMatch).map(r=>`<article class="card"><div class="card-top"><span class="meta">${r.id} · ${r.type}</span>${badge(r.priority)}</div><h3>${r.description}</h3><p><strong>Potential impact:</strong> ${r.potentialImpact}</p><p><strong>Mitigation:</strong> ${r.mitigation}</p><p><strong>Status:</strong> ${r.status}</p></article>`).join("")}
function renderWeekly(){document.getElementById("weeklyGrid").innerHTML=state.data.weekly.map(d=>`<article class="card"><span class="meta">${d.audience}</span><h3>${d.section}</h3><p>${d.content}</p></article>`).join("")}
function renderDashboardViews(){const signals=filteredSignals();renderKpis(signals);renderPriority(signals);renderLatest(signals);renderBars(signals);renderSignalsTable()}
function renderAll(){renderDashboardViews();renderCompetitors();renderCustomerMap();renderTechnology();renderRegisters();renderWeekly()}
async function init(){try{await loadData();setup();renderAll()}catch(e){document.querySelector("main").innerHTML=`<section class="panel" style="padding:24px"><h2>Data loading problem</h2><p>${e.message}</p><p>Check that all JSON files are uploaded inside <strong>offroad-intelligence/data/</strong>.</p></section>`}}init();
