const state={data:{},filters:{industry:'all',signalType:'all',entityType:'all',search:''},newsMode:'all'};
const defaults={meta:{segments:['Construction','Agriculture','Material Handling','Turf','Offroad'],perspectives:[]},signals:[],competitors:[],customers:[],technologies:[],opportunities:[],risks:[],weekly:[],research:[],keyfigures:[],customerProfiles:[],competitorProfiles:[],benchmarking:[],newsRaw:{lastUpdated:'',news:[]}};
const files={meta:'data/meta.json',signals:'data/signals.json',competitors:'data/competitors.json',customers:'data/customers.json',technologies:'data/technologies.json',opportunities:'data/opportunities.json',risks:'data/risks.json',weekly:'data/weekly.json',research:'data/research.json',keyfigures:'data/keyfigures.json',customerProfiles:'data/customer_profiles.json',competitorProfiles:'data/competitor_profiles.json',benchmarking:'data/benchmarking.json'};
async function fetchOptional(path,fallback){try{const r=await fetch(path,{cache:'no-store'}); if(!r.ok)return fallback; return await r.json()}catch(e){return fallback}}
async function loadNewsFeed(){for(const p of ['../news-data.json','./news-data.json','data/news-data.json']){const d=await fetchOptional(p,null); if(d&&Array.isArray(d.news))return d} return defaults.newsRaw}
async function loadData(){const entries=await Promise.all(Object.entries(files).map(async([k,p])=>[k,await fetchOptional(p,defaults[k])])); state.data=Object.fromEntries(entries); state.data.newsRaw=await loadNewsFeed();}
const norm=v=>String(v||'').toLowerCase();
const cleanText=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const extractUrl=v=>{const s=String(v||''); const m=s.match(/https?:\/\/[^\s"<>]+/); return m?m[0]:''};
const badge=p=>`<span class="badge ${norm(p).split(/[ &/]+/)[0]||'other'}">${cleanText(p)}</span>`;
const tag=t=>t?`<span class="tag">${cleanText(t)}</span>`:'';
const list=a=>Array.isArray(a)&&a.length?`<ul>${a.map(x=>`<li>${cleanText(x)}</li>`).join('')}</ul>`:'<p>Not populated yet</p>';
const countBy=(arr,fn)=>arr.reduce((a,x)=>{const k=fn(x)||'Other';a[k]=(a[k]||0)+1;return a},{});
const topN=(obj,n=6)=>Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,n);
function isOffroadRelevant(n){const auto=norm(n.auto_cv);const cat=norm(cleanText(n.category));const cvOk=auto.includes('cv')||auto.includes('commercial');const catOk=['construction','agriculture','material','handling','turf','offroad','off-highway','off-hihgway'].some(x=>cat.includes(x));return cvOk&&catOk}
function entityType(n){const sec=norm(n.section); if(sec.includes('competitor'))return 'Competitor'; if(sec.includes('customer'))return 'Customer'; return 'News & Trends'}
function industry(n){const c=norm(cleanText(n.category)); if(c.includes('material')||c.includes('handling')||c.includes('forklift'))return 'Material Handling'; if(c.includes('agri')||c.includes('tractor'))return 'Agriculture'; if(c.includes('turf'))return 'Turf'; if(c.includes('offroad')||c.includes('off-highway')||c.includes('off-hihgway'))return 'Offroad'; if(c.includes('construction')||c.includes('mining'))return 'Construction'; return cleanText(n.category)||'Other'}
function signalType(n){const txt=norm([n.headline,n.summary,n.category,n.company].map(cleanText).join(' ')); if(/autonom|automation|remote|robot|ai /.test(txt))return 'Autonomy / AI'; if(/electric|electrification|battery|ev|hydrogen|fuel cell/.test(txt))return 'Electrification'; if(/plant|facility|investment|factory|opens|opening|production site|manufacturing hub|campinas|brazil/.test(txt))return 'Investment / Footprint'; if(/acquires|acquisition|partnership|joint venture|collaboration|minority holding|loi|mou/.test(txt))return 'Partnership / M&A'; if(/revenue|sales|results|outlook|profit|financial|q1|q2|q3|h1/.test(txt))return 'Financial / Market'; if(/launch|new model|introduces|showcase|series|product/.test(txt))return 'Product / Launch'; if(/sustainab|circular|recycled|renewable|foam|material/.test(txt))return 'Sustainability / Materials'; if(/china|tariff|geopolitical|export|market share|competition/.test(txt))return 'Market / Competition'; return 'Other Signal'}
function technologyTags(n){const txt=norm([n.headline,n.summary,n.category].map(cleanText).join(' ')); const tags=[]; if(/autonom|remote|robot|automation|ai /.test(txt))tags.push('Automation / Autonomy'); if(/electric|battery|ev|hydrogen|fuel cell/.test(txt))tags.push('Electrification'); if(/connect|digital|fleet|software|data/.test(txt))tags.push('Connectivity / Digital'); if(/seat|cab|cabin|operator|comfort|ergonom/.test(txt))tags.push('Operator Environment'); if(/circular|recycled|renewable|material|foam|sustainab/.test(txt))tags.push('Sustainable Materials'); if(/brazil|argentina|mexico|india|china|north america|europe/.test(txt))tags.push('Regional Footprint'); return tags.length?tags:['General Market Signal']}
function classifyNews(n){return {...n,_type:entityType(n),_industry:industry(n),_signalType:signalType(n),_tech:technologyTags(n),_url:extractUrl(n.url)||extractUrl(n.headline),_company:cleanText(n.company),_headline:cleanText(n.headline),_summary:cleanText(n.summary),_date:cleanText(n.date),_auto:cleanText(n.auto_cv),_category:cleanText(n.category),_section:cleanText(n.section)}}
function allRelevantNews(){return (state.data.newsRaw.news||[]).filter(isOffroadRelevant).map(classifyNews)}
function filteredNews(){let arr=allRelevantNews(); if(state.newsMode==='customer')arr=arr.filter(n=>n._type==='Customer'); if(state.newsMode==='competitor')arr=arr.filter(n=>n._type==='Competitor'); if(state.newsMode==='trend')arr=arr.filter(n=>n._type==='News & Trends'); if(state.filters.industry!=='all')arr=arr.filter(n=>n._industry===state.filters.industry); if(state.filters.signalType!=='all')arr=arr.filter(n=>n._signalType===state.filters.signalType); if(state.filters.entityType!=='all')arr=arr.filter(n=>n._type===state.filters.entityType); if(state.filters.search)arr=arr.filter(n=>norm(JSON.stringify(n)).includes(norm(state.filters.search))); return arr}
function setup(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=document.getElementById(b.dataset.view); if(t)t.classList.add('active')}); const sig=document.getElementById('signalTypeFilter'); [...new Set(allRelevantNews().map(n=>n._signalType))].sort().forEach(x=>sig.insertAdjacentHTML('beforeend',`<option>${x}</option>`)); document.getElementById('industryFilter').onchange=e=>{state.filters.industry=e.target.value;renderAll()}; document.getElementById('signalTypeFilter').onchange=e=>{state.filters.signalType=e.target.value;renderAll()}; document.getElementById('entityTypeFilter').onchange=e=>{state.filters.entityType=e.target.value;renderAll()}; document.getElementById('searchInput').oninput=e=>{state.filters.search=e.target.value;renderAll()}; document.getElementById('resetFilters').onclick=()=>{state.filters={industry:'all',signalType:'all',entityType:'all',search:''};['industryFilter','signalTypeFilter','entityTypeFilter'].forEach(id=>document.getElementById(id).value='all'); document.getElementById('searchInput').value=''; renderAll()}; [['showAllNews','all'],['showCustomerNews','customer'],['showCompetitorNews','competitor'],['showTrendNews','trend']].forEach(([id,mode])=>{const el=document.getElementById(id);if(el)el.onclick=()=>{state.newsMode=mode;renderDailyNews()}})}
function renderKpis(){const all=allRelevantNews(); const filtered=filteredNews(); const tech=new Set(all.flatMap(n=>n._tech)); document.getElementById('kpis').innerHTML=[['Relevant news',all.length],['Filtered view',filtered.length],['Mapped customers',all.filter(n=>n._type==='Customer').length],['Mapped competitors',all.filter(n=>n._type==='Competitor').length],['Signal types',new Set(all.map(n=>n._signalType)).size],['Tech themes',tech.size]].map(([l,v])=>`<article class="kpi"><span>${l}</span><strong>${v}</strong></article>`).join('')}
function renderClusters(){const arr=filteredNews(); const typeCounts=countBy(arr,n=>n._signalType); const cards=topN(typeCounts,6).map(([t,c])=>{const examples=arr.filter(n=>n._signalType===t).slice(0,3); const industries=[...new Set(examples.map(n=>n._industry))].join(', '); return `<article class="signal-card"><div class="card-top">${badge(t)}<span class="meta">${c} items</span></div><h3 class="cluster-title">${t}</h3><p class="source-note">Main industries: ${industries||'n/a'}</p><div>${examples.map(n=>tag(n._company)).join('')}</div><div><div class="label">Example source evidence</div><ul>${examples.map(n=>`<li>${n._headline}</li>`).join('')}</ul></div><div class="confidence">Generated from Daily News source layer. Analyst confirmation still required for recommendations.</div></article>`}).join(''); document.getElementById('clusterGrid').innerHTML=cards||'<article class="signal-card">No relevant Daily News signals found.</article>'}
function renderTopEntities(){const arr=filteredNews(); const entities=topN(countBy(arr,n=>n._company),10); document.getElementById('topEntities').innerHTML=entities.map(([name,c])=>`<div class="compact-row"><div>${tag(name)}</div><div><strong>${name}</strong><p class="source-note">${c} linked news signal(s)</p></div><div>${tag(arr.find(n=>n._company===name)?._industry||'')}</div></div>`).join('')||'<p style="padding:18px">No mapped entities.</p>'}
function renderBars(){const counts=countBy(filteredNews(),n=>n._industry); const max=Math.max(1,...Object.values(counts)); document.getElementById('bars').innerHTML=topN(counts,8).map(([n,c])=>`<div><div class="bar-label"><strong>${n}</strong><em>${c}</em></div><div class="track"><div class="fill" style="width:${c/max*100}%"></div></div></div>`).join('')||'<p class="source-note">No category mix available.</p>'}
function renderSignalRadar(){const arr=filteredNews(); const techCounts=countBy(arr.flatMap(n=>n._tech),x=>x); document.getElementById('signalRadar').innerHTML=topN(techCounts,12).map(([t,c])=>{const examples=arr.filter(n=>n._tech.includes(t)).slice(0,4);return `<article class="card"><div class="card-top"><h3>${t}</h3>${badge(c+' signals')}</div><p class="source-note">Mapped from Daily News headlines, summaries and categories.</p><ul>${examples.map(n=>`<li>${n._company}: ${n._headline}</li>`).join('')}</ul></article>`}).join('')||'<article class="card">No technology themes detected.</article>'}
function renderDailyNews(){const rn=filteredNews(); const byType=countBy(rn,n=>n._type); document.getElementById('dailyNewsSummary').innerHTML=[['Shown items',rn.length],['Customers',byType.Customer||0],['Competitors',byType.Competitor||0],['News & Trends',byType['News & Trends']||0],['Updated',state.data.newsRaw.lastUpdated?new Date(state.data.newsRaw.lastUpdated).toLocaleDateString():'n/a']].map(([l,v])=>`<article class="kpi"><span>${l}</span><strong>${v}</strong></article>`).join(''); document.getElementById('dailyNewsTable').innerHTML=`<table><thead><tr><th>Date</th><th>Entity Type</th><th>Company</th><th>Industry</th><th>Signal Type</th><th>Detected Tech / Trend</th><th>Headline / Source Evidence</th><th>Summary</th><th>URL</th></tr></thead><tbody>${rn.map(n=>`<tr><td>${n._date}</td><td>${badge(n._type)}</td><td><strong>${n._company}</strong></td><td>${n._industry}</td><td>${badge(n._signalType)}</td><td>${n._tech.map(tag).join('')}</td><td class="signal-source"><strong>${n._headline}</strong></td><td>${n._summary}</td><td>${n._url?`<a class="news-link" href="${n._url}" target="_blank" rel="noopener noreferrer">Open source</a>`:'No URL'}</td></tr>`).join('')}</tbody></table>`}
function renderSignalsTable(){const signals=state.data.signals||[]; document.getElementById('signalsTable').innerHTML=`<table><thead><tr><th>ID</th><th>Priority</th><th>Perspective</th><th>Signal</th><th>Why it matters</th><th>Recommended action</th></tr></thead><tbody>${signals.map(s=>`<tr><td>${s.id||''}</td><td>${badge(s.priority||'Medium')}</td><td>${s.perspective||''}</td><td><strong>${cleanText(s.signal)}</strong></td><td>${cleanText(s.why)}</td><td>${cleanText(s.action)}</td></tr>`).join('')}</tbody></table>`}
function renderRelationships(){document.getElementById('relationshipGrid').innerHTML=(state.data.signals||[]).map(s=>`<article class="relationship-card"><div class="card-top"><span class="meta">${s.id||''}</span>${badge(s.priority||'Medium')}</div><h3>${cleanText(s.signal)}</h3><p>${cleanText(s.why)}</p></article>`).join('')||'<article class="relationship-card">No curated relationships yet.</article>'}
function renderCustomerProfiles(){document.getElementById('customerProfiles').innerHTML=(state.data.customerProfiles||[]).map(c=>{const l1=c.level1PermanentFacts||{},l2=c.level2QuarterlyFacts||{},l3=c.level3DynamicIntelligence||{};return `<article class="profile-card"><div class="profile-head"><div><span class="meta">${c.customerId||''}</span><h3>${cleanText(c.name)}</h3></div>${badge('Customer')}</div><div class="profile-columns"><div class="info-box"><strong>Permanent facts</strong><p><b>HQ:</b> ${cleanText(l1.headquarters)}</p><p><b>Segments:</b> ${(l1.coreSegments||[]).join('; ')}</p></div><div class="info-box"><strong>Quarterly facts</strong><p><b>Revenue:</b> ${cleanText(l2.revenue)}</p><p><b>Employees:</b> ${cleanText(l2.employees)}</p></div><div class="info-box"><strong>Dynamic intelligence</strong><p><b>Themes:</b> ${(l3.technologyThemes||[]).join('; ')}</p><p><b>Competitor exposure:</b> ${(l3.competitorExposure||[]).join('; ')}</p></div><div class="info-box"><strong>Actions</strong>${list(l3.nextActions)}</div></div></article>`}).join('')||'<article class="profile-card">No customer profiles found.</article>'}
function renderCompetitorProfiles(){document.getElementById('competitorProfiles').innerHTML=(state.data.competitorProfiles||[]).map(c=>{const l1=c.level1PermanentFacts||{},l2=c.level2QuarterlyFacts||{},l3=c.level3DynamicIntelligence||{};return `<article class="profile-card"><div class="profile-head"><div><span class="meta">${c.competitorId||''}</span><h3>${cleanText(c.name)}</h3></div>${badge('Competitor')}</div><div class="profile-columns"><div class="info-box"><strong>Permanent facts</strong><p><b>HQ:</b> ${cleanText(l1.headquarters)}</p><p><b>Products:</b> ${(l1.coreProducts||[]).join('; ')}</p></div><div class="info-box"><strong>Quarterly facts</strong><p><b>Revenue:</b> ${cleanText(l2.revenue)}</p><p><b>Employees:</b> ${cleanText(l2.employees)}</p></div><div class="info-box"><strong>Strengths</strong>${list(l3.strengths)}</div><div class="info-box"><strong>Questions to ask</strong>${list(l3.questionsToAsk)}<p><b>Counter-message:</b> ${cleanText(l3.grammerCounterMessage)}</p></div></div></article>`}).join('')||'<article class="profile-card">No competitor profiles found.</article>'}
function renderBenchmarking(){document.getElementById('benchmarkGrid').innerHTML=(state.data.benchmarking||[]).map(b=>`<article class="profile-card"><div class="profile-head"><div><span class="meta">${b.benchmarkId||''} · ${b.type||''}</span><h3>${cleanText(b.title)}</h3></div></div>${list((b.dimensions||[]).map(d=>`${cleanText(d.dimension)}: ${cleanText(d.comment||d.value||'')}`))}</article>`).join('')||'<article class="profile-card">No benchmarks found.</article>'}
function renderKeyFigures(){document.getElementById('keyFigureGrid').innerHTML=(state.data.keyfigures||[]).map(k=>`<article class="profile-card"><div class="profile-head"><div><span class="meta">${k.entityType||''} · ${k.entityId||''}</span><h3>${cleanText(k.name)}</h3></div></div><p><b>Revenue:</b> ${cleanText(k.revenue)}</p><p><b>Employees:</b> ${cleanText(k.employees)}</p><p><b>Headquarters:</b> ${cleanText(k.headquarters)}</p><p><b>Source:</b> ${cleanText(k.source)}</p></article>`).join('')||'<article class="profile-card">No key figures found.</article>'}
function renderMatrix(){const comps=state.data.competitors||[]; document.getElementById('matrixTable').innerHTML=`<table><thead><tr><th>Customer</th>${comps.map(c=>`<th>${cleanText(c.name)}</th>`).join('')}<th>Next action</th></tr></thead><tbody>${(state.data.customers||[]).map(c=>`<tr><td><strong>${cleanText(c.customer)}</strong><br>${cleanText(c.segment)}</td>${comps.map(comp=>`<td>${(c.competitorIds||[]).includes(comp.id)?'●':''}</td>`).join('')}<td>${cleanText(c.nextAction)}</td></tr>`).join('')}</tbody></table>`}
function renderTechnology(){document.getElementById('technologyGrid').innerHTML=(state.data.technologies||[]).map(t=>`<article class="card"><div class="card-top"><h3>${cleanText(t.theme)}</h3>${badge(t.relevance||'Medium')}</div><p><b>Maturity:</b> ${cleanText(t.maturity)}</p><p><b>Segments:</b> ${cleanText(t.segments)}</p><p>${cleanText(t.watchSignals)}</p></article>`).join('')||'<article class="card">No technology records found.</article>'}
function renderHeatmap(){const o=state.data.opportunities||[],r=state.data.risks||[]; const cells=[['High opportunity',o.filter(x=>x.priority==='High')],['High risk',r.filter(x=>x.priority==='High')],['Other opportunity',o.filter(x=>x.priority!=='High')],['Other risk',r.filter(x=>x.priority!=='High')]]; document.getElementById('heatmapGrid').innerHTML=cells.map(([t,arr])=>`<article class="heat-cell"><h3>${t}</h3>${list(arr.map(x=>x.opportunity||x.description))}</article>`).join('')}
function renderAll(){renderKpis();renderClusters();renderTopEntities();renderBars();renderSignalRadar();renderDailyNews();renderSignalsTable();renderRelationships();renderCustomerProfiles();renderCompetitorProfiles();renderBenchmarking();renderKeyFigures();renderMatrix();renderTechnology();renderHeatmap()}
async function init(){try{await loadData();setup();renderAll()}catch(e){document.querySelector('main').innerHTML=`<section class="panel" style="padding:24px"><h2>Data loading problem</h2><p>${e.message}</p><p>Check data files and root news-data.json.</p></section>`}}
init();
