const state={data:{},filters:{segment:'all',perspective:'all',priority:'all',search:''},newsMode:'all'};
const files={meta:'data/meta.json',signals:'data/signals.json',competitors:'data/competitors.json',customers:'data/customers.json',technologies:'data/technologies.json',opportunities:'data/opportunities.json',risks:'data/risks.json',weekly:'data/weekly.json',research:'data/research.json',keyfigures:'data/keyfigures.json',customerProfiles:'data/customer_profiles.json',competitorProfiles:'data/competitor_profiles.json',benchmarking:'data/benchmarking.json',evidence:'data/evidence.json',assessments:'data/assessments.json'};
const defaults={meta:{segments:['Agriculture','Construction','Material Handling','Turf','Offroad'],perspectives:['Sales','R&D','Product Management','Innovation','Procurement','Strategy']},signals:[],competitors:[],customers:[],technologies:[],opportunities:[],risks:[],weekly:[],research:[],keyfigures:[],customerProfiles:[],competitorProfiles:[],benchmarking:[],evidence:[],assessments:[],newsRaw:{lastUpdated:'',news:[]}};
async function fetchOptional(path,fallback){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)return fallback;return await r.json()}catch(e){return fallback}}
async function loadData(){const entries=await Promise.all(Object.entries(files).map(async([k,p])=>[k,await fetchOptional(p,defaults[k])]));state.data=Object.fromEntries(entries);state.data.newsRaw=await loadNewsFeed();seedFallbackAssessments();}
async function loadNewsFeed(){for(const p of ['../news-data.json','./news-data.json','data/news-data.json']){const d=await fetchOptional(p,null);if(d&&Array.isArray(d.news))return d}return defaults.newsRaw}
const norm=v=>String(v||'').toLowerCase();
const cleanText=v=>String(v||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const extractUrl=v=>{const m=String(v||'').match(/https?:\/\/[^\s"<>]+/);return m?m[0]:''};
const safeHtml=v=>cleanText(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const setHtml=(id,html)=>{const el=document.getElementById(id);if(el)el.innerHTML=html;};
const badge=p=>`<span class="badge ${norm(p)}">${safeHtml(p)}</span>`;
const tag=t=>`<span class="tag">${safeHtml(t)}</span>`;
const list=a=>Array.isArray(a)&&a.length?`<ul>${a.map(x=>`<li>${safeHtml(x)}</li>`).join('')}</ul>`:'<span class="muted">Not populated yet</span>';
const byIds=(arr,ids)=>arr.filter(x=>ids?.includes(x.id));
const searchMatch=o=>!state.filters.search||norm(JSON.stringify(o)).includes(norm(state.filters.search));
const segMatch=(v,s)=>s==='all'||norm(v).includes(norm(s))||norm(v).includes('all offroad');
function isOffroadRelevant(n){const auto=norm(n.auto_cv);const cat=norm(cleanText(n.category));return (auto.includes('cv')||auto.includes('commercial'))&&['construction','agriculture','material','handling','turf','offroad','off-highway'].some(x=>cat.includes(x));}
function newsType(n){const sec=norm(n.section);if(sec.includes('competitor'))return 'Competitor';if(sec.includes('customer'))return 'Customer';return 'News & Trends'}
function relevantNews(){let arr=(state.data.newsRaw.news||[]).filter(isOffroadRelevant).filter(searchMatch);if(state.newsMode==='customer')arr=arr.filter(n=>newsType(n)==='Customer');if(state.newsMode==='competitor')arr=arr.filter(n=>newsType(n)==='Competitor');if(state.newsMode==='trend')arr=arr.filter(n=>newsType(n)==='News & Trends');return arr;}
function filteredSignals(){return (state.data.signals||[]).filter(s=>segMatch(s.segment||s.industrySegment||'',state.filters.segment)&&(state.filters.perspective==='all'||s.perspective===state.filters.perspective)&&(state.filters.priority==='all'||s.priority===state.filters.priority)&&searchMatch(s))}
function confidenceFromPriority(p){return p==='High'?'Medium':p==='Low'?'Low':'Medium'}
function assessmentForSignal(id){return (state.data.assessments||[]).find(a=>a.signalId===id)}
function evidenceForSignal(id){return (state.data.evidence||[]).filter(e=>(e.linkedSignalIds||[]).includes(id))}
function signalById(id){return (state.data.signals||[]).find(s=>s.id===id||s.signalId===id)}
function seedFallbackAssessments(){if((state.data.assessments||[]).length)return;state.data.assessments=(state.data.signals||[]).slice(0,3).map((s,i)=>({assessmentId:`ASM-AUTO-${String(i+1).padStart(3,'0')}`,signalId:s.id,title:s.signal,assessment:s.why||'Analyst assessment not populated yet.',businessImplication:s.why||'Business implication should be added by Market Intelligence.',confidence:confidenceFromPriority(s.priority),forecast:'Forecast statement not populated yet.',timeHorizon:'To be defined',owner:s.owner||'Market Intelligence',reviewDate:s.date||'',opportunityIds:[],riskIds:[]}));}
function setup(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=document.getElementById(b.dataset.view);if(v)v.classList.add('active')});const seg=document.getElementById('segmentFilter'),per=document.getElementById('perspectiveFilter'),pf=document.getElementById('priorityFilter'),si=document.getElementById('searchInput'),rf=document.getElementById('resetFilters');if(seg)(state.data.meta.segments||[]).forEach(x=>seg.insertAdjacentHTML('beforeend',`<option>${safeHtml(x)}</option>`));if(per)(state.data.meta.perspectives||[]).forEach(x=>per.insertAdjacentHTML('beforeend',`<option>${safeHtml(x)}</option>`));if(seg)seg.onchange=e=>{state.filters.segment=e.target.value;renderAll()};if(per)per.onchange=e=>{state.filters.perspective=e.target.value;renderAll()};if(pf)pf.onchange=e=>{state.filters.priority=e.target.value;renderAll()};if(si)si.oninput=e=>{state.filters.search=e.target.value;renderAll()};if(rf)rf.onclick=()=>{state.filters={segment:'all',perspective:'all',priority:'all',search:''};if(seg)seg.value='all';if(per)per.value='all';if(pf)pf.value='all';if(si)si.value='';renderAll()};[['showAllNews','all'],['showCustomerNews','customer'],['showCompetitorNews','competitor'],['showTrendNews','trend']].forEach(([id,mode])=>{const el=document.getElementById(id);if(el)el.onclick=()=>{state.newsMode=mode;renderDailyNews();}})}
function entityTags(s){return [...byIds(state.data.competitors||[],s.competitorIds),...byIds(state.data.customers||[],s.customerIds),...byIds(state.data.technologies||[],s.technologyIds)].map(x=>tag(x.name||x.customer||x.theme)).join('')}
function businessImplication(s){const a=assessmentForSignal(s.id);return a?.businessImplication||s.why||'Business implication not populated yet.'}
function assessmentLink(s){const a=assessmentForSignal(s.id);return a?`<span class="tag">${safeHtml(a.assessmentId)}</span>`:'<span class="muted">No assessment</span>'}
function renderKpis(signals){const kpis=[['Signals',signals.length],['Assessments',(state.data.assessments||[]).length],['Evidence items',(state.data.evidence||[]).length],['Opportunities',(state.data.opportunities||[]).length],['High risks',(state.data.risks||[]).filter(r=>r.priority==='High').length],['News updated',state.data.newsRaw.lastUpdated?new Date(state.data.newsRaw.lastUpdated).toLocaleDateString():'n/a']];setHtml('kpis',kpis.map(([l,v])=>`<div class="kpi"><span>${safeHtml(l)}</span><strong>${safeHtml(v)}</strong></div>`).join(''))}
function renderOverview(signals){const top=signals.slice(0,3);setHtml('overviewSignalsGrid',top.map(s=>{const a=assessmentForSignal(s.id);const ev=evidenceForSignal(s.id);return`<article class="signal-card"><div>${badge(s.priority||'Medium')} ${a?badge(a.confidence||'Medium'):''}<span class="meta"> ${safeHtml(s.id||'')}</span></div><h3>${safeHtml(s.signal)}</h3><p><b>Business implication:</b> ${safeHtml(businessImplication(s))}</p><p><b>Evidence:</b> ${ev.length?`${ev.length} source${ev.length>1?'s':''}`:'0 sources'} · <b>Assessment:</b> ${a?safeHtml(a.assessmentId):'not linked'}</p><p><b>Action:</b> ${safeHtml(s.action)}</p></article>`}).join('')||'<p class="empty">No signals available.</p>');const ass=(state.data.assessments||[]).filter(searchMatch).slice(0,2);setHtml('overviewAssessmentsGrid',ass.map(a=>`<article class="profile-card"><div class="profile-head"><div><span class="meta">${safeHtml(a.assessmentId)} · ${safeHtml(a.signalId)}</span><h3>${safeHtml(a.title)}</h3></div>${badge(a.confidence||'Medium')}</div><div class="info-box"><strong>Business implication</strong>${safeHtml(a.businessImplication)}</div><div class="info-box"><strong>Forecast</strong>${safeHtml(a.forecast)}</div></article>`).join('')||'<p class="empty">No assessments available.</p>');setHtml('overviewOpportunities',overviewList((state.data.opportunities||[]).filter(o=>o.priority==='High').slice(0,4),'opportunity'));setHtml('overviewRisks',overviewList((state.data.risks||[]).filter(r=>r.priority==='High').slice(0,4),'risk'));}
function overviewList(arr,type){if(!arr.length)return'<p class="empty">No high-priority items yet.</p>';return arr.map(x=>`<div class="compact-row"><div>${badge(x.priority||'Medium')}</div><div><h4>${safeHtml(x.opportunity||x.description||x.riskDescription||x.title)}</h4><p>${safeHtml(x.nextAction||x.mitigation||x.potentialImpact||x.whyAttractive||'')}</p></div></div>`).join('')}
function renderSignalsTable(){const signals=filteredSignals();setHtml('signalsTable',`<table><tr><th>ID</th><th>Priority</th><th>Confidence</th><th>Evidence</th><th>Perspective</th><th>Signal</th><th>Linked entities</th><th>Business implication</th><th>Recommended action</th><th>Assessment</th></tr>${signals.map(s=>{const a=assessmentForSignal(s.id);const e=evidenceForSignal(s.id);return`<tr><td>${safeHtml(s.id||'')}</td><td>${badge(s.priority||'Medium')}</td><td>${a?badge(a.confidence||'Medium'):'<span class="muted">No assessment</span>'}</td><td>${e.length?`${e.length} source${e.length>1?'s':''}`:'0 sources'}</td><td>${safeHtml(s.perspective)}</td><td>${safeHtml(s.signal)}</td><td>${entityTags(s)}</td><td>${safeHtml(businessImplication(s))}</td><td>${safeHtml(s.action)}</td><td>${assessmentLink(s)}</td></tr>`}).join('')}</table>`)}
function renderAssessments(){const arr=(state.data.assessments||[]).filter(searchMatch);setHtml('assessmentSummary',[['Assessments',arr.length],['High confidence',arr.filter(a=>a.confidence==='High').length],['Medium confidence',arr.filter(a=>a.confidence==='Medium').length],['Low confidence',arr.filter(a=>a.confidence==='Low').length]].map(([l,v])=>`<div class="kpi"><span>${l}</span><strong>${v}</strong></div>`).join(''));setHtml('assessmentGrid',arr.map(a=>{const s=signalById(a.signalId)||{};const ev=evidenceForSignal(a.signalId);return`<article class="profile-card"><div class="profile-head"><div><span class="meta">${safeHtml(a.assessmentId)} · linked to ${safeHtml(a.signalId)}</span><h3>${safeHtml(a.title)}</h3></div>${badge(a.confidence||'Medium')}</div><div class="info-box"><strong>Layer 1 · Evidence</strong>${ev.length?`<ul>${ev.map(e=>`<li>${safeHtml(e.evidenceId)} · ${safeHtml(e.title)} · ${safeHtml(e.sourceName)} · Reliability ${safeHtml(e.reliability)}</li>`).join('')}</ul>`:'<span class="muted">No evidence linked yet.</span>'}</div><div class="info-box"><strong>Layer 2 · Interpretation</strong><b>Signal:</b> ${safeHtml(s.signal||a.title)}<br><b>Analyst assessment:</b> ${safeHtml(a.assessment)}<br><b>Business implication:</b> ${safeHtml(a.businessImplication)}</div><div class="info-box"><strong>Layer 3 · Decision support</strong><b>Forecast:</b> ${safeHtml(a.forecast)}<br><b>Time horizon:</b> ${safeHtml(a.timeHorizon)}<br><b>Owner:</b> ${safeHtml(a.owner)}<br><b>Review:</b> ${safeHtml(a.reviewDate)}</div><div class="entity-flow">${(a.opportunityIds||[]).map(tag).join('')}${(a.riskIds||[]).map(tag).join('')}</div></article>`}).join('')||'<p class="empty">No assessments found.</p>')}
function renderDailyNews(){const rn=relevantNews();const byType=rn.reduce((a,n)=>(a[newsType(n)]=(a[newsType(n)]||0)+1,a),{});setHtml('dailyNewsSummary',[['Relevant items',rn.length],['Customers',byType.Customer||0],['Competitors',byType.Competitor||0],['News & Trends',byType['News & Trends']||0]].map(([l,v])=>`<div class="kpi"><span>${l}</span><strong>${v}</strong></div>`).join(''));setHtml('dailyNewsTable',`<table><tr><th>Date</th><th>Type</th><th>Auto/CV</th><th>Category</th><th>Company / Entity</th><th>Headline</th><th>Source summary</th><th>Source URL</th></tr>${rn.map(n=>{const url=extractUrl(n.url)||extractUrl(n.headline);return`<tr><td>${safeHtml(n.date)}</td><td>${badge(newsType(n))}</td><td>${safeHtml(n.auto_cv)}</td><td>${safeHtml(n.category)}</td><td>${safeHtml(n.company)}</td><td>${safeHtml(n.headline)}</td><td>${safeHtml(n.summary)}</td><td>${url?`<a class="news-link" href="${url}" target="_blank" rel="noopener">Open source</a>`:'No URL'}</td></tr>`}).join('')}</table>`)}
function simpleCards(id,arr,titleField,bodyField){setHtml(id,(arr||[]).filter(searchMatch).map(x=>`<article class="profile-card"><span class="meta">${safeHtml(x.id||x.customerId||x.competitorId||x.benchmarkId||x.entityId||'')}</span><h3>${safeHtml(x[titleField]||x.name||x.customer||x.title||x.theme)}</h3><p>${safeHtml(x[bodyField]||x.description||x.mainPositioning||x.nextAction||'')}</p></article>`).join('')||'<p class="empty">No items available.</p>')}
function renderRelationships(){setHtml('relationshipGrid',(state.data.signals||[]).filter(searchMatch).map(s=>`<article class="relationship-card"><span class="meta">${safeHtml(s.id||'')}</span>${badge(s.priority||'Medium')}<h3>${safeHtml(s.signal)}</h3><div class="entity-flow">${tag('Signal')}<span class="arrow">→</span>${entityTags(s)||tag('No linked entity')}</div></article>`).join(''))}
function renderCustomerProfiles(){simpleCards('customerProfiles',state.data.customerProfiles,'name','profileStatus')}
function renderCompetitorProfiles(){simpleCards('competitorProfiles',state.data.competitorProfiles,'name','profileStatus')}
function renderBenchmarking(){simpleCards('benchmarkGrid',state.data.benchmarking,'title','type')}
function renderKeyFigures(){simpleCards('keyFigureGrid',state.data.keyfigures,'name','source')}
function renderMatrix(){const comps=state.data.competitors||[];setHtml('matrixTable',`<table><tr><th>Customer</th>${comps.map(c=>`<th>${safeHtml(c.name)}</th>`).join('')}<th>Next action</th></tr>${(state.data.customers||[]).map(c=>`<tr><td>${safeHtml(c.customer)}<br><span class="muted">${safeHtml(c.segment)}</span></td>${comps.map(comp=>`<td>${(c.competitorIds||[]).includes(comp.id)?'●':''}</td>`).join('')}<td>${safeHtml(c.nextAction)}</td></tr>`).join('')}</table>`)}
function renderTechnology(){setHtml('technologyGrid',(state.data.technologies||[]).filter(searchMatch).map(t=>`<article class="card"><h3>${safeHtml(t.theme)}</h3>${badge(t.relevance||'Medium')}<p><b>Maturity:</b> ${safeHtml(t.maturity)}<br><b>Affected segments:</b> ${safeHtml(t.segments)}<br><b>Watch signals:</b> ${safeHtml(t.watchSignals)}</p><div class="info-box"><strong>V16.5 investment lens</strong>Market adoption, customer adoption, competitor adoption, GRAMMER readiness and revenue potential can be added here in the next data enrichment step.</div></article>`).join('')||'<p class="empty">No technology data available.</p>')}
function renderHeatmap(){const cells=[['High opportunity',(state.data.opportunities||[]).filter(o=>o.priority==='High')],['High risk',(state.data.risks||[]).filter(r=>r.priority==='High')],['Medium opportunity',(state.data.opportunities||[]).filter(o=>o.priority==='Medium')],['Other risks',(state.data.risks||[]).filter(r=>r.priority!=='High')]];setHtml('heatmapGrid',cells.map(([t,arr])=>`<article class="heat-cell"><h3>${t}</h3>${arr.length?list(arr.map(x=>x.opportunity||x.description||x.title)):'<span class="muted">No items yet</span>'}</article>`).join(''))}
function renderAll(){const signals=filteredSignals();renderKpis(signals);renderOverview(signals);renderSignalsTable();renderAssessments();renderDailyNews();renderRelationships();renderCustomerProfiles();renderCompetitorProfiles();renderBenchmarking();renderKeyFigures();renderMatrix();renderTechnology();renderHeatmap()}
async function init(){try{await loadData();setup();renderAll()}catch(e){const m=document.querySelector('main');if(m)m.innerHTML=`<h3>Data loading problem</h3><p>${safeHtml(e.message)}</p><p>Check JSON files inside offroad-intelligence/data/ and root news-data.json.</p>`}}
init();
